[project]
name = "langgraph-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=0.3.23",
    "langchain-groq>=0.3.2",
    "langgraph>=0.3.31",
    "nest-asyncio>=1.6.0",
    "pyppeteer>=2.0.0",
]
